#!/bin/sh
# Native ppc64le build of vkd3d-proton. Mirrors dxvk-ppc64le/build-dxvk.sh:
# everything defaults to -mcpu=power8 so the binaries run on POWER8 and
# POWER9 alike, and the flag is passed explicitly rather than inherited from
# whatever the distro's makepkg.conf happens to say.
#
#   ./ppc64le/build-native.sh              # power8 floor, ./build-native, -j8
#   PPC_MCPU=power9 ./ppc64le/build-native.sh
#   BUILD_DIR=/tmp/b JOBS=32 ./ppc64le/build-native.sh
#
# ninja does not read MAKEFLAGS; -j is passed explicitly. Left alone ninja
# picks core-count+2, which on a big POWER box has exhausted memory and
# killed links before.
set -eu
repo=$(cd "$(dirname "$0")/.." && pwd)

MCPU=${PPC_MCPU:-power8}
BUILD_DIR=${BUILD_DIR:-$repo/build-native}
JOBS=${JOBS:-8}

if command -v widl >/dev/null 2>&1; then
    WIDL=$(command -v widl)
else
    WIDL=$repo/ppc64le/idl/widl-shim.sh
fi

machine_file=$repo/ppc64le/.native-generated.ini
cat > "$machine_file" <<EOF
# Generated by build-native.sh — do not edit, do not commit.
[binaries]
widl = '$WIDL'

[built-in options]
# -fno-strict-aliasing: COM-in-C reads typed object pointers through
# IUnknown** constantly (vkd3d code and its test suite both). gcc 16.1.1 at
# -O3 on ppc64le exploits the aliasing UB in
# test_destruction_notifier_interfaces into a stack-slot-sharing miscompile
# (A/B/A-verified: stock crashes, this flag fixes, stock crashes again).
# Wine builds with the same flag for the same reason.
c_args = ['-mcpu=$MCPU', '-fno-strict-aliasing']
cpp_args = ['-mcpu=$MCPU', '-fno-strict-aliasing']
EOF

echo "target: -mcpu=$MCPU  jobs: $JOBS  build: $BUILD_DIR  widl: $WIDL"

if [ ! -f "$BUILD_DIR/build.ninja" ]; then
    meson setup "$BUILD_DIR" "$repo" \
        --native-file "$machine_file" \
        --buildtype release \
        -Denable_tests=true
fi

ninja -C "$BUILD_DIR" -j "$JOBS"

echo "built:"
ls "$BUILD_DIR"/libs/d3d12core/*.so "$BUILD_DIR"/libs/d3d12/*.so 2>/dev/null || true
